/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "HunterMussel",
  "tagline": "AI Process Management & DevOps",
  "favicon": "img/favicon.ico",
  "url": "https://huntermussel.com",
  "baseUrl": "/",
  "organizationName": "huntermussel",
  "projectName": "huntermussel",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "ignore",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": false,
        "blog": {
          "routeBasePath": "blog",
          "blogTitle": "HunterMussel Blog",
          "blogDescription": "Articles on process management, AI automation, and DevOps.",
          "postsPerPage": 10,
          "showReadingTime": true,
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright 2026 HunterMussel"
          }
        },
        "theme": {
          "customCss": "./src/index.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ]
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/og-default.svg",
    "navbar": {
      "title": "Hunter Mussel",
      "logo": {
        "alt": "HunterMussel Target Logo",
        "src": "img/logo.svg",
        "srcDark": "img/logo.svg",
        "width": 28,
        "height": 28
      },
      "items": [
        {
          "label": "Services",
          "href": "/#services",
          "position": "right"
        },
        {
          "label": "Cases",
          "href": "/#cases",
          "position": "right"
        },
        {
          "label": "About",
          "href": "/#about",
          "position": "right"
        },
        {
          "label": "Tecnologies",
          "href": "/#technologies",
          "position": "right"
        },
        {
          "label": "BLOG",
          "to": "/blog",
          "position": "right"
        },
        {
          "label": "Contact us",
          "href": "/#contact",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "metadata": [
      {
        "name": "description",
        "content": "Automate and optimize your company's process management with Artificial Intelligence, intelligent automation, and DevOps."
      },
      {
        "name": "keywords",
        "content": "process management, artificial intelligence, AI automation, DevOps, workflow automation, RPA, cloud infrastructure"
      },
      {
        "name": "robots",
        "content": "index,follow,max-image-preview:large"
      }
    ],
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "headTags": [
    {
      "tagName": "script",
      "attributes": {
        "type": "application/ld+json"
      },
      "innerHTML": "{\"@context\":\"https://schema.org\",\"@type\":\"Organization\",\"@id\":\"https://huntermussel.com/#organization\",\"name\":\"HunterMussel\",\"url\":\"https://huntermussel.com\",\"description\":\"Automate and optimize your company's process management with Artificial Intelligence, intelligent automation, and DevOps.\",\"logo\":{\"@type\":\"ImageObject\",\"url\":\"https://huntermussel.com/img/og-default.svg\"},\"founder\":{\"@type\":\"Person\",\"name\":\"Iago Mussel\",\"jobTitle\":\"CEO & Founder\"},\"areaServed\":\"Worldwide\"}"
    }
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
